name: Create Release on Tag

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 

    - name: Get Tag Message
      id: get_tag_message
      run: |
        TAG_MESSAGE=$(git tag -n1 ${GITHUB_REF##*/})
        echo "tag_message=$TAG_MESSAGE" >> $GITHUB_OUTPUT

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TRANSLATE_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: ${{ steps.get_tag_message.outputs.tag_message }}
        draft: false
        prerelease: false
